<?php
// This script and data application were generated by AppGini 4.52
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	$d=dirname(__FILE__);
	include("$d/defaultLang.php");
	include("$d/language.php");
	include("$d/lib.php");
	@include("$d/hooks/disease_symptoms.php");
	include("$d/disease_symptoms_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('disease_symptoms');
	if(!$perm[0]){
		echo StyleSheet();
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		echo '<script language="javaScript">setInterval("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "disease_symptoms";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(
		"`disease_symptoms`.`id`" => "ID",
		"`diseases1`.`short_name` /* Disease */" => "Disease",
		"`symptoms1`.`name` /* Symptom */" => "Symptom",
		"`disease_symptoms`.`expected_probability`" => "Expected probability",
		"`disease_symptoms`.`minimum`" => "Minimum",
		"`disease_symptoms`.`maximum`" => "Maximum",
		"`disease_symptoms`.`reading_other_value`" => "Reading other value",
		"`disease_symptoms`.`comments`" => "Comments"
	);
	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(
		"`disease_symptoms`.`id`" => "ID",
		"`diseases1`.`short_name` /* Disease */" => "Disease",
		"`symptoms1`.`name` /* Symptom */" => "Symptom",
		"`disease_symptoms`.`expected_probability`" => "Expected probability",
		"`disease_symptoms`.`minimum`" => "Minimum",
		"`disease_symptoms`.`maximum`" => "Maximum",
		"`disease_symptoms`.`reading_other_value`" => "Reading other value",
		"`disease_symptoms`.`comments`" => "Comments"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(
		"`disease_symptoms`.`id`" => "ID",
		"`diseases1`.`short_name` /* Disease */" => "Disease",
		"`symptoms1`.`name` /* Symptom */" => "Symptom",
		"`disease_symptoms`.`expected_probability`" => "Expected probability",
		"`disease_symptoms`.`minimum`" => "Minimum",
		"`disease_symptoms`.`maximum`" => "Maximum",
		"`disease_symptoms`.`reading_other_value`" => "Reading other value",
		"`disease_symptoms`.`comments`" => "Comments"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(
		"`disease_symptoms`.`id`" => "ID",
		"`diseases1`.`short_name` /* Disease */" => "Disease",
		"`symptoms1`.`name` /* Symptom */" => "Symptom",
		"`disease_symptoms`.`expected_probability`" => "Expected probability",
		"`disease_symptoms`.`minimum`" => "Minimum",
		"`disease_symptoms`.`maximum`" => "Maximum",
		"`disease_symptoms`.`reading_other_value`" => "Reading other value",
		"`disease_symptoms`.`comments`" => "Comments"
	);

	$x->QueryFrom="`disease_symptoms` LEFT JOIN `diseases` as diseases1 ON `disease_symptoms`.`disease`=diseases1.`id` LEFT JOIN `symptoms` as symptoms1 ON `disease_symptoms`.`symptom`=symptoms1.`id` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->DataHeight = 300;
	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "disease_symptoms_view.php";
	$x->RedirectAfterInsert = "disease_symptoms_view.php?SelectedID=#ID#";
	$x->TableTitle = "Disease symptoms";
	$x->PrimaryKey = "`disease_symptoms`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(150, 300, 150, 150, 150, 150);
	$x->ColCaption = array("Disease", "Symptom", "Expected probability", "Minimum", "Maximum", "Reading other value");
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	$x->Template = 'templates/disease_symptoms_templateTV.html';
	$x->SelectedTemplate = 'templates/disease_symptoms_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	if($perm[2]==1){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `disease_symptoms`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='disease_symptoms' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `disease_symptoms`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='disease_symptoms' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`disease_symptoms`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}

	// handle date sorting correctly
	// end of date sorting handler

	// hook: disease_symptoms_init
	$render=TRUE;
	if(function_exists('disease_symptoms_init')){
		$args=array();
		$render=disease_symptoms_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: disease_symptoms_header
	$headerCode='';
	if(function_exists('disease_symptoms_header')){
		$args=array();
		$headerCode=disease_symptoms_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include("$d/header.php"); 
	}else{
		ob_start(); include("$d/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: disease_symptoms_footer
	$footerCode='';
	if(function_exists('disease_symptoms_footer')){
		$args=array();
		$footerCode=disease_symptoms_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include("$d/footer.php"); 
	}else{
		ob_start(); include("$d/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>