<?php
// This script and data application were generated by AppGini 4.52
// Download AppGini for free from http://www.bigprof.com/appgini/download/

	$d=dirname(__FILE__);
	include("$d/defaultLang.php");
	include("$d/language.php");
	include("$d/lib.php");
	@include("$d/hooks/patients.php");
	include("$d/patients_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('patients');
	if(!$perm[0]){
		echo StyleSheet();
		echo "<div class=\"error\">".$Translation['tableAccessDenied']."</div>";
		echo '<script language="javaScript">setInterval("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "patients";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(
		"`patients`.`id`" => "ID",
		"`patients`.`last_name`" => "Last name",
		"`patients`.`first_name`" => "First name",
		"`patients`.`gender`" => "Gender",
		"if(`patients`.`birth_date`,date_format(`patients`.`birth_date`,'%m/%d/%Y'),'')" => "Birth date",
		"`patients`.`age`" => "Age",
		"`patients`.`address`" => "Address",
		"`patients`.`city`" => "City",
		"`patients`.`state`" => "State",
		"`patients`.`zip`" => "Zip",
		"`patients`.`home_phone`" => "Home phone",
		"`patients`.`work_phone`" => "Work phone",
		"`patients`.`mobile`" => "Mobile",
		"`patients`.`other_details`" => "Other details",
		"`patients`.`comments`" => "Comments",
		"DATE_FORMAT(`patients`.`filed`, '%c/%e/%Y %l:%i%p')" => "Filed",
		"DATE_FORMAT(`patients`.`last_modified`, '%c/%e/%Y %l:%i%p')" => "Last modified"
	);
	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(
		"`patients`.`id`" => "ID",
		"`patients`.`last_name`" => "Last name",
		"`patients`.`first_name`" => "First name",
		"`patients`.`gender`" => "Gender",
		"if(`patients`.`birth_date`,date_format(`patients`.`birth_date`,'%m/%d/%Y'),'')" => "Birth date",
		"`patients`.`age`" => "Age",
		"`patients`.`address`" => "Address",
		"`patients`.`city`" => "City",
		"`patients`.`state`" => "State",
		"`patients`.`zip`" => "Zip",
		"`patients`.`home_phone`" => "Home phone",
		"`patients`.`work_phone`" => "Work phone",
		"`patients`.`mobile`" => "Mobile",
		"`patients`.`other_details`" => "Other details",
		"`patients`.`comments`" => "Comments",
		"DATE_FORMAT(`patients`.`filed`, '%c/%e/%Y %l:%i%p')" => "Filed",
		"DATE_FORMAT(`patients`.`last_modified`, '%c/%e/%Y %l:%i%p')" => "Last modified"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(
		"`patients`.`id`" => "ID",
		"`patients`.`last_name`" => "Last name",
		"`patients`.`first_name`" => "First name",
		"`patients`.`gender`" => "Gender",
		"`patients`.`birth_date`" => "Birth date",
		"`patients`.`age`" => "Age",
		"`patients`.`address`" => "Address",
		"`patients`.`city`" => "City",
		"`patients`.`state`" => "State",
		"`patients`.`zip`" => "Zip",
		"`patients`.`home_phone`" => "Home phone",
		"`patients`.`work_phone`" => "Work phone",
		"`patients`.`mobile`" => "Mobile",
		"`patients`.`other_details`" => "Other details",
		"`patients`.`comments`" => "Comments",
		"`patients`.`filed`" => "Filed",
		"`patients`.`last_modified`" => "Last modified"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(
		"`patients`.`id`" => "ID",
		"`patients`.`last_name`" => "Last name",
		"`patients`.`first_name`" => "First name",
		"`patients`.`gender`" => "Gender",
		"if(`patients`.`birth_date`,date_format(`patients`.`birth_date`,'%m/%d/%Y'),'')" => "Birth date",
		"`patients`.`age`" => "Age",
		"`patients`.`address`" => "Address",
		"`patients`.`city`" => "City",
		"`patients`.`state`" => "State",
		"`patients`.`zip`" => "Zip",
		"`patients`.`home_phone`" => "Home phone",
		"`patients`.`work_phone`" => "Work phone",
		"`patients`.`mobile`" => "Mobile",
		"`patients`.`other_details`" => "Other details",
		"`patients`.`comments`" => "Comments",
		"DATE_FORMAT(`patients`.`filed`, '%c/%e/%Y %l:%i%p')" => "Filed",
		"DATE_FORMAT(`patients`.`last_modified`, '%c/%e/%Y %l:%i%p')" => "Last modified"
	);

	$x->QueryFrom="`patients` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->DataHeight = 300;
	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingMultiSelection = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 20;
	$x->QuickSearch = 3;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "patients_view.php";
	$x->RedirectAfterInsert = "patients_view.php?SelectedID=#ID#";
	$x->TableTitle = "Patients";
	$x->PrimaryKey = "`patients`.`id`";
	$x->DefaultSortField = '1';
	$x->DefaultSortDirection = 'desc';

	$x->ColWidth   = array(120, 120, 70, 50, 150, 50, 50, 120, 120, 120);
	$x->ColCaption = array("Last name", "First name", "Gender", "Age", "City", "State", "Zip", "Home phone", "Work phone", "Mobile");
	$x->ColNumber  = array(2, 3, 4, 6, 8, 9, 10, 11, 12, 13);

	$x->Template = 'templates/patients_templateTV.html';
	$x->SelectedTemplate = 'templates/patients_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	if($perm[2]==1){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `patients`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='patients' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `patients`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='patients' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`patients`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}

	// handle date sorting correctly
	// end of date sorting handler

	// hook: patients_init
	$render=TRUE;
	if(function_exists('patients_init')){
		$args=array();
		$render=patients_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: patients_header
	$headerCode='';
	if(function_exists('patients_header')){
		$args=array();
		$headerCode=patients_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include("$d/header.php"); 
	}else{
		ob_start(); include("$d/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: patients_footer
	$footerCode='';
	if(function_exists('patients_footer')){
		$args=array();
		$footerCode=patients_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include("$d/footer.php"); 
	}else{
		ob_start(); include("$d/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>